name: uptimise
description: ""

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: # Unsupported OS(s) listed in comments
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/gen/app_icon.png
  adaptive_icon_foreground: assets/gen/adaptive_foreground.png
  adaptive_icon_background: assets/gen/adaptive_background.png

flutter_native_splash:
  color: "#F3F6FF"
  color_dark: "#2E3440"
  image: assets/gen/splash.png
  # android12: true
