name: uptimise
description: ""

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: # Unsupported OS(s) listed in comments
  animations: ^2.0.0
  auto_route: ^2.0.0
  cloud_firestore: ^2.0.0
  firebase_analytics: ^8.0.0 # macos
  firebase_auth: ^3.0.0
  firebase_core: ^1.0.0
  firebase_crashlytics: ^2.0.0 # web
  flutter:
    sdk: flutter
  flutter_hooks: 0.18.0
  flutter_keyboard_visibility: ^5.0.0 # macos
  flutter_speed_dial: ^4.0.0
  google_sign_in: ^5.0.0 # macos # TODO: figure out what to do for macos
  hooks_riverpod: ^1.0.0-dev.6
  jiffy: ^4.0.0
  logger: ^1.0.0
  responsive_builder: 0.4.1
  shared_preferences: ^2.0.0
  url_strategy: 0.2.0
  uuid: ^3.0.0
  # TODO: consider using https://pub.dev/packages/bitsdojo_window

dev_dependencies:
  auto_route_generator: ^2.0.0
  build_runner: ^2.0.0
  flutter_launcher_icons: 0.9.1
  flutter_native_splash: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: NotoMono
      fonts:
        - asset: assets/fonts/NotoMono-Regular.ttf
          weight: 400

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/gen/app_icon.png
  adaptive_icon_foreground: assets/gen/adaptive_foreground.png
  adaptive_icon_background: assets/gen/adaptive_background.png

flutter_native_splash:
  color: "#F3F6FF"
  color_dark: "#2E3440"
  image: assets/gen/splash.png
  # android12: true
