name: uptimise
description: ""

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: # Unsupported OS(s) listed in comments
  auto_route: ^2.0.0
  firebase_analytics: ^8.0.0 # macos
  firebase_core: ^1.0.0
  firebase_crashlytics: ^2.0.0 # web
  flutter:
    sdk: flutter
  flutter_hooks: 0.18.0
  flutter_keyboard_visibility: ^5.0.0 # macos
  hooks_riverpod: ^1.0.0-dev.5
  logger: ^1.0.0
  responsive_builder: 0.4.1
  shared_preferences: ^2.0.0
  url_strategy: 0.2.0

dev_dependencies:
  auto_route_generator: ^2.0.0
  build_runner: ^2.0.0
  flutter_launcher_icons: 0.9.0
  flutter_native_splash: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/gen/app_icon.png
  adaptive_icon_foreground: assets/gen/adaptive_foreground.png
  adaptive_icon_background: assets/gen/adaptive_background.png

flutter_native_splash:
  color: "#F3F6FF"
  color_dark: "#2E3440"
  image: assets/gen/splash.png
  # android12: true
